language: r
cache: packages
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
    secure: jqQpLaPQVZLuJgcvvRIf+M37gZIQ4RsoauMlVtGOexdcYZDp+2GQpleuJsupw+G8T72Bq8yTw6NQ4lNwxqCvxEh9dZwlVQQgBIVFX9g9CuIreWrQXOL4FwemOehUB1mU8BNUUNjNEDiwqp5d0zXLIBfevaF+tKPmRhRAH1XtAPn93G7RfMnCIMCa9oN+LDznQWv9HNLQ0pgF4o0dbGLBKpcSdDlRXPOgmMSkHi1OGmbtBewt/7bEMOFa8Fn0dM5KWdiqKpGKW9OySvBj9rDwYsRzGweTFIF0BK56wswv1QMMHP5NxmeC99/q4RzIE23h0QhZNkJPrAZrTqKJzQCB+MSX6xQKW2J4Au01X/DtqRo2j74jKFTMILY6k1SlO49pUT1sQVDdgoETt+jPn1HdkwzdY2riWdBxKedLXzRlBm5Zi0f474mQ7q4/Y6MruuuodIUvi2uFuRau+pJ3ukpamjB+8oTSTWyoTP9bpMRqBS10LgcT7CSJTYVii2CiaS3jKPXlWDS7hKTZcIA9r7reT8aQuZTQKjWDY4Vw75fE/KnaUOMkaaBB9aRoVUJODugeIUyiNX4Q+kq90y5jCxjnL28ZM2kRs4d3LzgqlRchEOe2Ju0womzyRA9SsI8HlOaWgmuSQ1MCXSrd8tVmVvJOgGp9Fh9K5LkXbkmBEcIjDU8=
